[package]
name = "rcdu"
version = "0.2.0"
edition = "2024"
rust-version = "1.85"
license = "MIT AND Zlib"
description = "Linux disk usage browser with ncdu-compatible imports and exports"
repository = "https://github.com/aditya-gupta-dev/rcdu"

[dependencies]
libc = "0.2"
zstd = { version = "0.13", default-features = false }
unicode-segmentation = "1"
unicode-width = { version = "0.2", default-features = false }

[profile.profiling]
inherits = "release"
debug = "line-tables-only"
strip = "none"

[profile.distribution]
inherits = "release"
lto = "thin"
codegen-units = 1
strip = "symbols"
